version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfull
      - ls
      - cd webapp/target
      - ls
artifacts:
  files:
    - /webapp/target/webapp.war
