kind: Deployment
apiVersion: apps/v1
metadata:
  name: depsec
spec:
  selector:
    matchLabels:
      name: pradeepsec
  replicas: 3
  template:
    metadata:
      name: pod
      labels:
        name: pradeepsec
    spec:
      containers:
      - name: cont
        image: imagename
        ports:
        - containerPort: 80
